pm/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to, direct_to_template

urlpatterns = patterns('pm.views',
    url(r'^$', redirect_to, {'url': '/pm/inbox/', 'permanent': False}, name="pm"),
    #url(r'^send/$', 'send', name='pm_send'),
    url(r'^send/to/(?P<uid>\d+)$', 'send', name='pm_send'),
    url(r'^view/(?P<num>\d+)$', 'view', name='pm_view'),

    url(r'^inbox/$', 'pm_inbox', {"page" : 1}, name='pm_inbox'),
    url(r'^inbox/(?P<page>\d+)$', 'pm_inbox', name='pm_inbox'),
    url(r'^outbox/$', 'pm_outbox', {"page" : 1}, name='pm_outbox'),
    url(r'^outbox/(?P<page>\d+)$', 'pm_outbox', name='pm_outbox'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to
from django.views.generic.simple import direct_to_template

from OET.events.forms import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('OET.views',
    url(r'^$', redirect_to, {'url': '/events/', 'permanent': False}, name='home'),
    #url(r'^oet/', include('OET.events.urls')),

    url(r'^users/login/$', 'login_user', name='login'),
    url(r'^users/login/$', 'login_user', name='login'),
    url(r'^users/logout/$', 'logout_user', name='logout'),
    url(r'^users/registration/$', 'registration', name='registration'),

    url(r'^users/profile/$', 'my_profile', name='user_profile'),
    url(r'^users/profile/(?P<user>\d+)$', 'user_profile', name='user_profile'),

    url(r'^not-implemented/$', direct_to_template, {'template':'not_implemented.html'}, name='not_implemented'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^pm/', include('OET.pm.urls')),
)

from OET.events.urls import urlpatterns as events_urlpatterns
urlpatterns += events_urlpatterns

pm/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    text = models.CharField(max_length=500)
    from_user = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_from_user")
    to_user = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_to_user")
    unread = models.BooleanField()
    datetime = models.DateTimeField()

    class Meta:
        ordering = ('-datetime',)

pm/views.py
# -*- coding: utf8 -*-

from django.forms import ModelForm
from models import Message
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.template import RequestContext
from django.http import Http404
import datetime
from django.contrib.auth.models import User

class SendForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('to_user', 'from_user', 'datetime', 'unread')

@login_required
def send(request, uid=None):
    template = "pm/send.html"
    template_ok = "pm/sent.html"

    if request.method != 'POST':
        if uid is not None:
            try:
                user = User.objects.get(id=uid)
            except User.DoesNotExists:
                raise Http404
            form = SendForm(initial={"to_user":user})
        else:
            raise Http404
        return render_to_response(template,
                            {"form" : form,
                             "uid" : uid},
                            context_instance=RequestContext(request))
    
    if uid is not None:
        try:
            user = User.objects.get(id=uid)
        except User.DoesNotExists:
            raise Http404
    else:
        raise Http404
    form = SendForm(request.POST)
    #form.additional_data = {"place_str" : request.POST["id_place_str"]}
    place = None
    if form.is_valid():
        obj = form.save(commit=False)
        obj.from_user = request.user
        obj.to_user = user
        obj.datetime = datetime.datetime.today()
        obj.unread = True
        obj = form.save(commit=True)
    else:
        return render_to_response(template,
                            {"form" : form},
                            context_instance=RequestContext(request))
    return render_to_response(template_ok,
                            {'next' : '/pm/view/%s' % (obj.id)},
                            context_instance=RequestContext(request))

@login_required
def view(request, num):
    template = "pm/view.html"
    msg = Message.objects.get(id=num)
    if not((msg.from_user == request.user) or (msg.to_user == request.user)):
        return render_to_response("pm/denied.html",
                            context_instance=RequestContext(request))
    if request.user == msg.to_user:
        msg.unread = False
        msg.save()
    return render_to_response(template,
                            {"msg" : msg},
                            context_instance=RequestContext(request))

@login_required
def pm_inbox(request, page):
    template = "pm/list.html"
    on_page = 5
    s = ((int(page)-1)*on_page)
    msgs = Message.objects.filter(to_user=request.user)[s:s+on_page]

    return render_to_response(template,
                            {"msgs" : msgs, "name" : "Inbox"},
                            context_instance=RequestContext(request))

@login_required
def pm_outbox(request, page):
    template = "pm/list.html"
    on_page = 5
    s = ((int(page)-1)*on_page)
    msgs = Message.objects.filter(from_user=request.user)[s:s+on_page]

    return render_to_response(template,
                            {"msgs" : msgs, "name" : "Outbox"},
                            context_instance=RequestContext(request))

templates/pm/denied.html
{% extends "base.html" %}

{% block body %}

Просмотр сообщения запрещен

{% endblock %}

templates/pm/list.html
{% extends "base.html" %}

{% block body %}


<nav id="content-nav" class="menu clearfix">
    <ul>
        <li id="inbox" {% if name == "Inbox" %} class="active"{% endif %}><a href="{% url pm_inbox %}">Входящие</a></li>
        <li id="outbox" {% if name == "Outbox" %} class="active"{% endif %}><a href="{% url pm_outbox %}">Отправленные</a></li>
    </ul>
</nav>
<div class="content">
	<table border="1" cellpadding="0" cellspacing="0" width="100%">

	<tr class="even">
	    <td>Время</td>
	    <td>Адресат</td>
	    <td>Адресант</td>
	    <td width="60%">Заголовок</td>
	</tr>

	{% for msg in msgs %}
	<tr class="odd">
	    <td>{{ msg.datetime|date:"d.m.Y H:i" }}</td>
	    <td><a href="{% url user_profile msg.from_user.id %}">{{ msg.from_user }}</a></td>
	    <td><a href="{% url user_profile msg.to_user.id %}">{{ msg.to_user }}</a></td>
	    <td>{% if msg.unread %}<b>{% endif %}<a href="{% url pm_view msg.id %}">{{ msg.title }}</a>{% if msg.unread %}</b>{% endif %}</td>
	</tr>
	{% endfor %}

	</table>
</div>
{% endblock %}

templates/pm/send.html
{% extends "base.html" %}

{% block body %}
<div role="view">
<h3>Отправка сообщения:</h3>

<form action="{% url pm_send uid %}" method="post">{% csrf_token %}
<p><label for="id_title">Заголовок</label> <input id="id_title" type="text" name="title" class="large_input" maxlength="100"></p>
<p><label for="id_text">Сообшение</label> <textarea rows="5" cols="20" id="id_text" type="textarea" class="large_input" name="text"></textarea></p>

<input type="submit" value="Отправить" />

</form>
</div>
{% endblock %}

templates/pm/sent.html
{% extends "redirect_2.html" %}

{% block message %}
<div role="view">
<h3>Сообщение отправлено успешно</h3>
</div>
{% endblock %}

templates/pm/view.html
{% extends "base.html" %}

{% block body %}
<div role="view">
	Личное сообщение от: <a href="{% url user_profile msg.from_user.id %}">{{ msg.from_user }}</a><br>
	Кому: <a href="{% url user_profile msg.to_user.id %}">{{ msg.to_user }}</a><br>
	
	<b>{{ msg.title }}</b><br>
	{{ msg.text }}
</div>
{% endblock %}